use etlhive;
select * from healthcare;

-- Retrieve the names of all patients in the database.
select Name from healthcare;

-- List the unique medical conditions present in the dataset.
select distinct (Medical_Condition) from healthcare;

-- Find the total number of doctors in the healthcare system.
select count(distinct(Doctor)) from healthcare;

-- Retrieve the details of all female patients.
select * from healthcare where gender='female';

-- what is the average age of patients in the database.
select avg(age) from healthcare;

-- Identify the patients who have more than one medical condition.
select * from healthcare where Medical_Condition ='diabetes' and Medical_Condition in ('asthma','obesity','arthritis','hypertension','cancer')
or Medical_Condition='asthma' and Medical_Condition in ('obesity','arthritis','hypertension','cancer')
or Medical_Condition='obesity' and Medical_Condition in ('arthritis','hypertension','cancer')
or Medical_Condition='arthritis' and Medical_Condition in ('hypertension','cancer')
or Medical_Condition='hypertension' and Medical_Condition in ('cancer');


-- List the names of all doctors.
select doctor from healthcare;

-- Identify the most common medical condition among patients.
select medical_condition,count(medical_condition) from healthcare group by Medical_Condition order by count(medical_condition) desc limit 1 ;

-- Find the patients who are older than 60 years and have diabetes.
select * from healthcare where age>60 and Medical_Condition='diabetes';

-- Calculate the total revenue generated by the healthcare system.
select sum(billing_amount) from healthcare;

-- Find the doctor with the oldest patient.
select doctor,age from healthcare order by age desc limit 1;

-- Calculate the average duration of medical visits.
select avg(duration) from healthcare;

-- Give the names of patients whose name starts with A.
select name from healthcare where name like 'A%';

-- How many male and female patients are there in dataset.
select gender,count(gender) from healthcare group by gender;

-- 	how many patients are normal.
select  count(*) from healthcare where test_results='normal';

-- how many patients are abnormal or Inconclusive.
select count(*) from healthcare where test_results in ( 'abnormal','Inconclusive');

-- how many patients of blood group AB+ are there of age above 52.
select count(*) from healthcare where Blood_Type='AB+' and age>52;

-- how many patients have paid the bill above 24890.
select count(*) from healthcare where Billing_Amount>24890;

-- what are the names of patients having Asthma.
select name,medical_condition from healthcare where medical_condition='asthma';

-- 	how many patients have cancer.
select count(*) from healthcare where medical_condition='cancer';

-- what are the names and blood groups of patients admitted to room no. 292.
select name,blood_type from healthcare where room_number=292;

-- how many males have Arthritis.
select count(*) from healthcare where Gender='male' and Medical_Condition='Arthritis';

--  How many patients were admitted to Harris and Sons hospital.
select count(*) from healthcare where hospital='Harris and Sons';

-- what are the names of patients whose Insurance Provider are Cigna.
select name,insurance_provider from healthcare where Insurance_Provider='cigna';

-- Name the Medical Condition having patients whose ages is greater than average age
select name, medical_condition,age from healthcare where age > (select avg(age) from healthcare);